### ISSUE TITLE
Improve speed of DenseTracker

### ISSUE THREAD

**Issue by strasdat** [strasdat/ScaViSLAM#9]
At the moment, we compute the error for each single pixel. This seems to be a waste of computation. 
- GPU: A good heuristic seems to be to only use every n-th pixel (especially for high pyramid levels).
- CPU: Select good pixels for tracker. (Either use Andrew Comport's approach or simply calculate error for FAST points.)

**Comment by strasdat** [comment]
CPU: try to use FAST features, this did not work well. But, using every 4th row and column seems to be a decent heuristic. Commited: https://github.com/strasdat/ScaViSLAM/commit/5fa165b648c03f8253fdbd79ee7d562790fbdb38

**Comment by pinglin** [comment]
Hi Hauke,

I also thought about this before.
If you look into the steepest descent term in Gauss-Newton formula, only those pixels with enough large gradient or with enough large photometric error will contribute to the update.
However, since we already parallelly calculate these in GPU, I don't expect much speed up with considering this.
How do you think?
Is your dense tracker exactly the same in DTAM?

**Comment by strasdat** [comment]
Hm, if we only use every 4th row and column, we could have a 16 x speed-up on the GPU. This would be especially important for low-end/middle class GPUs with low throughput. 
It is not exactly the same than DTAM but very similar.
